FROM apache/airflow:2.10.2-python3.10

# Install system dependencies if needed
USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc g++ && \
    rm -rf /var/lib/apt/lists/*

# Switch back to airflow user
USER airflow

# Copy requirements file
COPY requirements-airflow.txt /opt/airflow/

# Install Python packages
RUN pip install --no-cache-dir -r /opt/airflow/requirements-airflow.txt